<?php

namespace CategoryBundle\Repository;

/**
 * SpectacleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectacleRepository extends \Doctrine\ORM\EntityRepository
{
}
