services:
#    export.example:
#        class: ExportBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    export.admin.export:
        class: ExportBundle\Admin\ExportAdmin
        arguments: [~, ExportBundle\Entity\Export, UserBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Export }
