services:
    pao.menu_listener:
        class: PAOBundle\EventListener\MenuBuilderListener
        arguments: [~, PAOBundle\Entity\PAO, UserBundle:UserAdmin]
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    pao.admin.badge:
        class: PAOBundle\Admin\BadgeAdmin
        arguments: [~, PAOBundle\Entity\Badge, PAOBundle:BadgeAdmin]
        calls:
            - [ setTemplate, [edit, PAOBundle::base_edit.html.twig]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Badge }
