<?php

namespace ExportBundle\Repository;

/**
 * ExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportRepository extends \Doctrine\ORM\EntityRepository
{
}
