services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    user.admin.user:
        class: UserBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, UserBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
