services:
#    institution.example:
#        class: InstitutionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    institution.admin.institution:
        class: InstitutionBundle\Admin\InstitutionAdmin
        arguments: [~, InstitutionBundle\Entity\Institution, InstitutionBundle:InstitutionAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Institution }
