services:
    application_sonata_user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\User, ApplicationSonataUserBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
